### ISSUE TITLE
認証APIを実装する

### ISSUE THREAD

**Issue by minakamoto** [its-succ/dakoku#15]
#13 
の

> 認証
> front側で、google-sign-in後、google OAuthから返ってきたaccess-tokenなどを元に認証OKか検証する

**Comment by minakamoto** [comment]
参考

https://github.com/its-succ/dakoku/issues/13#issuecomment-345129515

**Comment by minakamoto** [comment]
現状、Googleのほかのサービス（Google Driveなど）を使用する予定はなく
認証だけで良いので、上の参考の
5)では新たにaccees tokenを取得しているが、
認証済みかどうかのチェックで良いはず

**Comment by sizuhiko** [comment]
認証済み == トークンから取得できるユーザー情報のメアドが `*.esm.co.jp` にマッチする

はチェックすると良いかもな、と思いました
