### ISSUE TITLE
Googleアカウントで認証できるようにする

### ISSUE THREAD

**Issue by fossamagna** [its-succ/dakoku#2]

**Comment by fossamagna** [comment]
https://github.com/pac4j/spark-pac4j を利用して OAuth2.0 で認証すればいいと思う。

**Comment by sizuhiko** [comment]
https://www.webcomponents.org/element/GoogleWebComponents/google-signin/elements/google-signin
使うとフロントで解決することもできますけどね

**Comment by fossamagna** [comment]
ということで、google-signinを試してみたい。

**Comment by minakamoto** [comment]
polymerでgoogle sign-in したあと、
backend側にgoogleから返ってきたaccess-tokenなどの情報を渡すAPIをたたく
